config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  get '/datos_receta', to: 'recipes#datos_receta', as: 'datos_receta'
  get '/eliminar_ingrediente', to: 'recipes#eliminar_ingrediente', as: 'eliminar_ingrediente'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"}
    resources :users do
      get 'user_check', :on => :collection
      get 'user_check2', :on => :collection
    end


  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'recipe_like', to: 'recipes#recipe_like', as: 'recipe_like'

  namespace 'api' do
    namespace 'v1' do
      resources :recipes
      get 'like', to: 'recipes#like', as: 'like'
    end 
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_attached_file :foto, styles: {recortada: "640x426#", thumb: "640x426" }
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: proc{ |att| att['name'].blank?}


  has_many :likes, dependent: :destroy



  def self.Recetas_con_mas_likes
      query = select("recipes.id, recipes.name, COUNT(l.recipe_id) as cantidad_likes, recipes.foto_file_name, recipes.created_at")
              .joins('INNER JOIN likes l ON recipes.id = l.recipe_id ')
			  .group(:name, :id,:created_at,:foto_file_name)
			  .order("cantidad_likes Desc")
   end






end

app/controllers/api/v1/recipes_controller.rb
module Api
	module V1
		class RecipesController < ApplicationController
			def index
				recipes = Recipe.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Loaded recipes', data:recipes},status: :ok
			end
			
			def show
				recipe = Recipe.find(params[:id]);
				render json: {status: 'SUCCESS', message:'Loaded recipe', data:recipe},status: :ok
			end
			
			def create
				recipe = Recipe.new(recipe_params);

				if recipe.save
					render json: {status: 'SUCCESS', message:'Saved recipe', data:recipe},status: :ok
				else
					render json: {status: 'ERROR', message:'Recipe not saved', data:recipe.errors},status: :unprocessable_entity
				end
			end

			def destroy
				recipe = Recipe.find(params[:id]);
				recipe.destroy
				render json: {status: 'SUCCESS', message:'Deleted recipe', data:recipe},status: :ok
			end

			def update
				recipe = Recipe.find(params[:id]);
				if recipe.update_attributes(recipe_params)
					render json: {status: 'SUCCESS', message:'Updated recipe', data:recipe},status: :ok
				else
					render json: {status: 'ERROR', message:'Recipe not updated', data:recipe.errors},status: :unprocessable_entity
				end
			end

			def like
				@like = Like.find_by(recipe_id: params[:receta], user_id: params[:usuario]);
				if @like.nil?
			      me_gusta = Like.create(recipe_id: params[:receta], user_id: params[:usuario]) 
					render json: {status: 'SUCCESS', message:'Recipe Liked', data:me_gusta},status: :ok
			    else
			      @like.delete 
					render json: {status: 'SUCCESS', message:'Recipe erased', data:@like},status: :ok
			    end
			end



			private

			def recipe_params
				params.permit(:name, :body, :user_id)	
			end
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :recipe_like]
  before_action :authenticate_user!

  # GET /recipes
  # GET /recipes.json
  def index
    @recipe = Recipe.new
    @recipes = current_user.recipes.page(params[:page]).per(15)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @likex = ActiveRecord::Base.connection.execute("SELECT FROM total_likes()")

    @likes = @recipe.likes.all.count
    @me_gusta = Like.find_by(recipe_id: @recipe.id, user_id: current_user.id)
    respond_to do |format|
        format.html
        format.pdf do
          pdf = RecipePdf.new(@recipe)
          send_data pdf.render, filename: "Receta##{@recipe.try(:name)}.pdf",
                                type: "application/pdf",
                                disposition: "inline"
        end
    end
  end

  def recipe_like
    @like = Like.find_by(recipe_id: @recipe.id, user_id: current_user.id)
    if @like.nil?
      @me_gusta = Like.create(recipe_id: @recipe.id, user_id: current_user.id) 
    else
      @like.delete 
    end


    @likes = @recipe.likes.all.count
    respond_to do |format|
      if @me_gusta.present?
        format.js {flash.now[:notice] = 'Te ha gustado la receta'} 
      else 
        format.js {} 
      end
    end
  end

  def datos_receta
    @recipe_edit = Recipe.find_by(id: params[:recipe])
    @recipe_edit.ingredients.build

    respond_to do |format|
      format.js #para que se puedan enviar los datos de la busqueda del @search de la gema
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe.ingredients.build
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        if params[:lista].present?
          params[:lista].each do |(c,ingrediente)|
            Ingredient.create(name: ingrediente, recipe_id:@recipe.id) if ingrediente != ""
          end
        end
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
        format.js {flash.now[:notice] = 'La receta se ha creado de forma exitosa.'} #ajax
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al crear la receta.'} #ajax
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)

        if params[:lista].present?
          params[:lista].each do |(c,ingrediente)|
            Ingredient.create(name: ingrediente, recipe_id:@recipe.id) if ingrediente != ""
          end
        end

        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
        format.js {flash.now[:notice] = 'La receta se ha actualizado de forma exitosa.'} 
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al actuar la receta.'} 
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
      format.js {flash.now[:notice] = 'La receta se ha eliminado de forma exitosa.'} #ajax
    end
  end

  def eliminar_ingrediente
    @ingredient = Ingredient.find_by_id(params[:id])
    @ingredient.destroy
    @index = params[:index] #para eliminar el ingrediente del formulario
    respond_to do |format|
      format.js 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :body, :foto, ingredients_attributes: Ingredient.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_datos_receta.html.erb
<% if @recipe_edit != nil%>
<!-- Modal -->
  <%= form_for(@recipe_edit, :method => :put, remote: true, html: {class: "formulario-validado-update"}) do |f| %> <!--ajax remote: true-->
  <div class="modal fade bd-example-modal-lg myupdaterecipe" id="myupdaterecipe" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Editar receta</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <div class="form-group">
            <div class="col-md-8">
             Nombre: <%= f.text_field :name, class: "form-control recipe_name",autofocus: true, minlength: "5", :required => "true"  %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <button type="button" class="btn btn-success btn-xs" onclick="miIngredienteEdit()">
               Añadir ingrediente
              </button>
            </div>
          </div>

           <div id="ingredientes" class="form-row">
              <%= f.fields_for :ingredients do |builder| %>
                <%= render 'ingredient', f:builder%>
              <%end%>
           </div>

          <%= fields_for :lista do |ff|%>
           <div id="ingredientes_edit" class="form-row">

           </div>
          <% end %>

          <div class="form-group">
            <%= f.label :body, "Descripción:", class: "control-label col-md-2"  %>
            <div class="col-md-12">
              <%= f.text_area :body, class: "form-control recipe_body",style:"height: 200px;", minlength: "20", :required => "true" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :foto, "Foto:", class: "control-label col-md-2"  %>
            <div class="col-md-12">
              <%= f.file_field :foto, class: "recipe_foto" %>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <%= submit_tag "Actualizar", class: "btn btn-primary", data: { disable_with: 'Actualizando' }%>
        </div>
      </div>
    </div>
  </div>
  <%end%>


  <script>
    $(".formulario-validado-update").validate();
  </script>
<%end%>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

            <%= form.fields_for :ingredients do |builder| %>
              <%= render 'ingredient', f:builder%>
            <%end%>

        <div class="field">
          <%= form.label :foto, "Foto:", class: "control-label col-md-2"  %>
          <div class="col-md-12">
            <%= form.file_field :foto, class: "recipe_foto" %>
          </div>
        </div>
  

  <div class="actions">
    <%= form.submit %>

  </div>
<% end %>

app/views/recipes/_ingredient.html.erb
<div class= "form-group col-md-4 ingredientes_añadidos" id="ingrediente_<%=f.object.id%>">


  <div class="input-group mb-2">
    <div class="input-group-prepend">
    	<div class="input-group-text">
    	<% if f.object.id !=nil %>
				<%= link_to '', eliminar_ingrediente_path(:id => f.object.id, :index => f.index), class: "fa fa-trash", remote:true, data: {confirm: "¿Está seguro que desea eliminarlo?"}, style:"color: rgb(144, 142, 142);" %>
		<%end%>
			</div>
    </div>



    <%= f.text_field :name, label:false, class:"recipe_ingredientes form-control", placeholder:"Ingrediente"  %>
  </div>


</div>

app/views/recipes/_recipe.html.erb
<div class="col-lg-4 col-md-6 px-md-2" id= "recipe_<%= recipe.id %>">
  <div class="card"> 
    <div class="card-header p-0 position-relative">
      <a href="#">

        <%= link_to recipe do %>
           <%= image_tag(recipe.foto.url(:recortada), :alt => "Card image cap", class: "card-img-bottom foto") %>
        <% end %>

        <span class="fa fa-book post-icon"></span>
      </a>
    </div>
    <div class="card-body">
      <h6 class="let-spa mb-3"><%= recipe.try(:created_at).strftime("%d-%m-%Y") %></h6>
      <h5 class="blog-title card-title">
        <a href="#">
        <%= link_to "#{recipe.name}", recipe %>
      </h5>
      <div class="row">
        <div class="col-12" style="text-align: right; color: #999;">
          <p>

            <%= link_to 'Editar', datos_receta_path(:recipe => recipe.try(:id)), class: "btn btn-default btn-xs", :remote => true, data: { disable_with: 'Cargando...' }  %>

            <%= link_to 'Eliminar', recipe_path(recipe), method: :delete, class: "btn btn-default btn-xs", remote:true, data: {confirm: "¿Está seguro que desea eliminarlo?", disable_with: 'Eliminando...'} %>

           


        </div>
        <% if recipe.likes.all.count != 0%>
          <%= recipe.likes.all.count %> <i class="fa fa-heart", style="color: rgb(227, 30, 38);"></i>
        <% end%>
      </div>
    </div>
  </div>
</div>

app/views/recipes/create.js.erb
  $("#mi_nueva_receta").modal('hide');
  $(".recipe_name").val('');
  $(".recipe_body").val('');
  $(".recipe_ingredientes").remove();
  $("#recipe_foto").val('');
  $(".ingredientes_añadidos").remove();

$(".container_recipes").prepend('<%= j render @recipe %>'); //Prepend before append

$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");
var orden=0;
setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/recipes/datos_receta.js.erb
$("#datos_receta").html("<%= escape_javascript(render("datos_receta"))%>")
$('#myupdaterecipe').modal('show');

app/views/recipes/destroy.js.erb
$("#recipe_<%= @recipe.id %>").remove();
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/eliminar_ingrediente.js.erb
$("#ingrediente_<%= @ingredient.id %>").remove();
$("#recipe_ingredients_attributes_<%= @index %>_id").remove();
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/recipes/index.html.erb
<style type="text/css">
  .mt-5, .my-5 {
    margin-top: 1rem !important;
  }

  .containerx {
      background-color: #ffffffed;
      margin-top: 0%;
      padding-top: 5% !important;
      padding-left: 2%;
      min-height: 50rem;
      overflow: hidden;
  }

  .receta {
    min-height: 100%;
    position: absolute;
    width: 100%;
    overflow: hidden;
  }
</style>


<!-- Modal -->
<%= form_for(@recipe, remote: true, html: {class: "formulario-validado-create"}) do |f| %> <!--ajax remote: true-->
<div class="modal fade bd-example-modal-lg" id="mi_nueva_receta" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Mi nueva receta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="form-group">
          <div class="col-md-8">
           Nombre: <%= f.text_field :name, class: "form-control recipe_name",autofocus: true, minlength: "5", :required => "true"  %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12">
            <button type="button" class="btn btn-success btn-xs" onclick="miIngrediente()">
             Añadir ingrediente
            </button>
          </div>
        </div>

        <%= fields_for :lista do |ff|%>
         <div id="ingredientes" class="form-row">



         </div>
        <% end %>

        <div class="form-group">
          <%= f.label :body, "Descripción:", class: "control-label col-md-2"  %>
          <div class="col-md-12">
            <%= f.text_area :body, class: "form-control recipe_body",style:"height: 200px;", :required => "true", minlength: "20" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :foto, "Foto:", class: "control-label col-md-2"  %>
          <div class="col-md-12">
            <%= f.file_field :foto, class: "recipe_foto" %>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <%= submit_tag "Crear", class: "btn btn-primary", data: { disable_with: 'Creando' }%>
      </div>
    </div>
  </div>
</div>
<%end%>
  <div id="datos_receta"><%= render 'datos_receta' %></div>


  <section class="blog receta" id="blog">   
    <div class="container containerx py-xl-5 py-lg-3">
    <div class="text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mi_nueva_receta">
        Nueva receta
      </button>
    </div>

      <h3 class="title-w3ls text-center text-bl mb-5">Mis recetas</h3>
      <div class="row container_recipes">
        <%= render @recipes%>
      </div>
      <div class="row">
        <%= paginate @recipes %>
      </div>
    </div>

  </section>



    <script>
      var orden=0;

      function miIngrediente() {
        orden=orden+1;
        var y = document.createElement("DIV");
        y.setAttribute("class", "form-group col-md-4 ingredientes_añadidos");
        var x = document.createElement("INPUT");
        x.setAttribute("type", "text");
        x.setAttribute("name", `lista[ingrediente_${orden}]`);
        x.setAttribute("class", "recipe_ingredientes form-control");
        x.setAttribute("id", `ingrediente_${orden}`);
        x.setAttribute("placeholder", `Ingrediente`);
        document.getElementById('ingredientes').appendChild(y).appendChild(x);
      }

      function miIngredienteEdit() {
        orden=orden+1;
        var y = document.createElement("DIV");
        y.setAttribute("class", "form-group col-md-4 ingredientes_añadidos");
        var x = document.createElement("INPUT");
        x.setAttribute("type", "text");
        x.setAttribute("name", `lista[ingrediente_${orden}]`);
        x.setAttribute("class", "recipe_ingredientes form-control");
        x.setAttribute("id", `ingrediente_${orden}`);
        x.setAttribute("placeholder", `Ingrediente`);
        document.getElementById('ingredientes_edit').appendChild(y).appendChild(x);
      }
    </script>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/recipe_like.js.erb
<%if @me_gusta.present?%>
  document.getElementById("me_gusta").style.color = "rgb(227, 30, 38)";
<%else%>
  document.getElementById("me_gusta").style.color = "#999";
<%end%>
$('#likes').html('<%= escape_javascript(render("likes")) %>');
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/recipes/show.html.erb
<style type="text/css">
	.containerx {
	    background-color: #ffffffed;
	    margin-top: -4%;
	    padding-top: 8% !important;
	    padding-left: 2%;

	}
</style>

<section class="w3ls-bnrbtm py-5 receta" id="about">
	<div class="container containerx py-xl-5 py-lg-3">

		<div class="row flex-row-reverse pb-5">
			<div class="col-lg-6">
				   <%= image_tag(@recipe.foto.url(:recortada), :alt => "Card image cap", class: "card-img-bottom foto") %>
			</div>
			<div class="col-lg-6 abou-right-w3layuts mt-5">
				<h3 class="mb-4"><%= @recipe.name %></h3>
				<h4 class="mb-4">Ingredientes:</h4>
				
				<ul class="ingredientes">
				    <% @recipe.ingredients.each do |ingrediente| %>
						<li type="disc"><%= ingrediente.name %></li>
				    <% end %>
				</ul>

			</div>
		</div>

		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 abou-right-w3layuts mt-5">
				<h3 class="mb-4">Preparación:</h3>
				<p style="font-size: 1.1em;"><%= @recipe.body %></p>
			</div>
		</div>
  		<div id="likes"><%= render 'likes' %></div>

	</div>

	   
</section>

<style type="text/css">
	.ingredientes{
    color: rgb(153, 153, 153);
    font-size: 22px !important;
    line-height: 2.1em;
	}
</style>

app/views/recipes/update.js.erb
$("#myupdaterecipe").modal('hide');

$("#recipe_<%= @recipe.id %>").remove();
$(".modal-backdrop").remove();
$(".container_recipes").prepend('<%= j render @recipe %>'); //Prepend before append

$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);